---
title: "Examine Life Expectancy"
author: "Lin Sung Chieh"
date: "August 27, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# use HTML is effective to Git

# Abstract

Here, we examine the cool life expectancy plot.

# Life Expectancy Analysis

We will first clean the data.

```{r}
#git status (folder still in working directory when folder is untracked)
#git add (put folder into stage)
```

```{r}
library(gapminder)
library(tidyverse)
gapminder_unfiltered %>%
  group_by(year, country) %>%
  summarise( Max_life = max(lifeExp)) #my way

data("gapminder_unfiltered")
gapminder_unfiltered %>%
  group_by(year) %>%
  filter(lifeExp == max(lifeExp)) %>%
  select(country, lifeExp, year) %>%
  arrange(year) ->
  sumdat
```

We will now recreate the plot from Oeppen and Vaupel (2002).

```{r}
sumdat %>%
  ggplot(aes(x= year,
             y = lifeExp))+
  geom_point(aes(color = country)) +
  geom_smooth(method = lm, se = F) +
  geom_point(shape = 1)
```

git status
git add
git commit -m "a nice message"
git push


